### ISSUE TITLE
기능 요구 사항 정하기

### ISSUE THREAD

**Issue by goni-ssi** [kucc/netflix#1]

**Comment by easymean** [comment]
태그 기능: 
1. 구성 요소: 태그 이름
2. 인스타그램 해쉬태그 형식으로

**Comment by easymean** [comment]
상단 검색 기능:
1. 태그를 사용하여 검색 가능
2. 선배 프로필 조회에 사용

**Comment by easymean** [comment]
프로필 생성 기능:
1. 로그인 전제
2. 우측 하단에 + 버튼을 클릭하면 프로필 생성 페이지로 넘어감
3. User Profile edit page가 뜸
4. 프로필 생성시 입력 정보
- 기본 정보 :  이름/학과/소속/가입시기/취미/관심분야/기술스택/한줄소개
- 사진업로드
- 관심분야/기술스택은 태그로 기록
- 깃헙 / 블로그 / 연락처 (이메일 혹은 핸드폰번호)

태그 기능
1. 태그 생성시 띄어쓰기로 입력하면 하나의 태그가 완성된다.
2. 태그는 각 항목당 최대 10개 생성가능
3. 태그 색상은 카테고리에 따라 다른 색을 지닌다. 태그 이름에 따라 x

프로필 수정기능:
1. 우측 상단에 아이콘을 클릭
2. 프로필 수정 클릭
3. 프로필 수정
4. 저장하기 클릭

프로필 삭제 기능:
공개/비공개 토글로 가능
db에서 삭제는 불가능

프로필 상세 조회:
1. 카드 리스트에서 카드 선택
2. 모달에 상세 정보가 표시
3. 프로필 생성시와 유사한 포맷

**Comment by easymean** [comment]
로그인 기능
1. 첫 화면에서 이메일과 비밀번호를 입력하면 로그인가능하다.
2. 이메일 비밀번호 입력 후 엔터 -> 로그인
2. 만약 이메일이 존재하지 않거나 비밀번호가 일치하지 않는다면 '아이디 혹은 비밀번호가 일치하지 않습니다' 메세지 통일

회원가입 기능
1. 첫 화면에서 회원가입을 누르면 회원가입 화면으로 이동한다.
2. 회원가입시 필요한 정보는 이메일/비밀번호/가입년도 이다.
3. 이메일 중복 체크: 이메일 입력 후 중복 체크를 누르면 중복 체크 가능
++ 이메일 인증기능: 시간 남으면
4. 비밀번호 확인 기능: 비밀번호를 한번더 입력해서 일치여부 확인
5. 가장 하단에 회원가입 버튼 클릭시 회원가입 완료
6. 비밀번호 암호화: bcrypt

**Comment by easymean** [comment]
알림창 기능
1. 상대방이 ? 버튼을 클릭하면 알림이간다.
2. 알림 취소 불가능
3. 알림은 ~주까지 보관가능
